site_name: Mingyu Medical Notes
site_url: https://myZ555.github.io/

theme:
  name: material
  language: zh

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link

  palette:

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: 切换到深色模式

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式

plugins:
  - search
  - awesome-pages
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - abbr

  - toc:
      permalink: true

  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css
