site_name: Mingyu Medical Notes
site_url: https://myZ555.github.io/

theme:
  name: material
  language: zh

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true